# Define the CPU architecture name
CPU = avr

# Include the Contiki-NG root directory
CONTIKI_NG = $(realpath $(dir $(lastword $(MAKEFILE_LIST)))../../..)

# Add CPU-specific source files
CPU_SRC += arch/cpu/avr/contiki-conf.h